language: python

python:
  - "2.7"
  - "3.4"
  - "pypy"

script:
  - python setup.py test

install:
  - pip install Django
  - pip install sqlalchemy --use-mirrors
  - if ! python --version 2>&1 | grep -q -i pypy ; then pip install Pillow --use-mirrors; fi

notifications:
  email: false
  irc: "irc.freenode.org#factory_boy"
